### ISSUE TITLE
arcs for two links from one node to another lie on top of each other

### ISSUE THREAD

**Issue by FedorIVS** [kunyuan/DiagramWanderer#3]
If I create two propagator lines that go from one node to another (possible scenario for diagrams in the Hubbard model), then the programme will create the correct arcs, but they will sit on top of each other. There should be an "if" statement, that distinguishes this case from two opposite propagators and creates the path for both lines on different sides of the shortest connecting path, so that they can be distinguished from each other.

I tried fixing this myself, but run into trouble as I don't fully understand the way the arc function (or maybe paths) work.

Would be great if you could resolve this.

I attached an example file, where the programme fails.
[lambda_N6.js.zip](https://github.com/kunyuan/DiagramWanderer/files/351166/lambda_N6.js.zip)

**Comment by kunyuan** [comment]
Dear Fedor,
    It should work now. Please have pull the new code from Github.

Best,
Kun

**Comment by FedorIVS** [comment]
It's actually still not doing what it should, as now the arrow on one of the two lines is pointing in the wrong direction. They should be both coming from one node and pointing at another node.

**Comment by FedorIVS** [comment]
I solved the problem now. You can merge the new DiagWand.html

Cheers,

Fedor

**Comment by kunyuan** [comment]
Hi Fedor,
    Somehow, in your branch, I didn’t find “diagram_2.js” file which is required by “DiagWand.html”. Could you please add one and submit a pull request again? Thanks!

Best,
Kun

**Comment by FedorIVS** [comment]
done.

**Comment by kunyuan** [comment]
Dear Fedor,
    I have merged your fix.

Best,
Kun
